#!/usr/bin/env python3
"""
Compile Raycast script commands from raycast/text/*.txt.

Each source file is a block of text that you want to paste somewhere. This
turns each one into a Raycast script command, so it shows up in Raycast's root
search by name and pastes into the frontmost app.

    ---
    name: thermo
    icon: 🌡️        # optional, defaults to 📋
    ---
    <everything from here to EOF is the text, byte for byte>

The body is never parsed, quoted, indented or escaped, and it is baked into the
generated script at build time — nothing is read from the .txt at run time.

Usage:
    ./scripts/build-raycast-text-paste-scripts.py            # build
    ./scripts/build-raycast-text-paste-scripts.py --check    # verify output is up to date

Generated scripts land in raycast/scripts/generated/ and are picked up by
Raycast automatically. Deleting a source file removes its command on the next
build; hand-written scripts in that directory are never touched.
"""
import argparse
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
SRC_DIR = REPO / "raycast" / "text"
OUT_DIR = REPO / "raycast" / "scripts" / "generated"

DELIM = "---\n"
KNOWN_KEYS = {"name", "icon"}
DEFAULT_ICON = "📋"

# Every generated file carries this, so cleanup can tell its own output from a
# hand-written script that happens to live in the same directory.
MARKER = "@generated by scripts/build-raycast-text-paste-scripts.py"

# Raycast expands these inside a *snippet*. A script has no such machinery, so
# it would paste the literal text "{clipboard}" — silently wrong, and only
# noticed after you have pasted it somewhere that mattered.
PLACEHOLDERS = ("{clipboard}", "{cursor}", "{date", "{time", "{uuid}", "{argument")


def slug(name):
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def parse(path):
    raw = path.read_text(encoding="utf-8")
    if not raw.startswith(DELIM):
        raise ValueError(f"{path.name}: must start with a '---' front-matter delimiter")
    _, rest = raw.split(DELIM, 1)
    if DELIM not in rest:
        raise ValueError(f"{path.name}: front matter is not closed with '---'")
    front, body = rest.split(DELIM, 1)

    meta = {}
    for lineno, line in enumerate(front.strip().split("\n"), start=2):
        if not line.strip():
            continue
        key, sep, value = line.partition(":")
        if not sep:
            raise ValueError(f"{path.name}:{lineno}: expected 'key: value', got {line!r}")
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        meta[key.strip()] = value

    unknown = set(meta) - KNOWN_KEYS
    if unknown:
        raise ValueError(f"{path.name}: unknown front-matter key(s): {', '.join(sorted(unknown))}")
    if not meta.get("name"):
        raise ValueError(f"{path.name}: 'name' is required and must be non-empty")
    if not body.strip():
        raise ValueError(f"{path.name}: body is empty")

    hit = next((p for p in PLACEHOLDERS if p in body), None)
    if hit:
        raise ValueError(
            f"{path.name}: body contains '{hit}', a Raycast snippet placeholder that a script "
            f"cannot expand — it would paste the literal text"
        )

    return {"name": meta["name"], "icon": meta.get("icon") or DEFAULT_ICON,
            "text": body, "source": path}


def heredoc_delimiter(core):
    """A delimiter that cannot collide with a line of the body."""
    base, n, delim = "RAYCAST_TEXT", 0, "RAYCAST_TEXT"
    lines = set(core.split("\n"))
    while delim in lines:
        n += 1
        delim = f"{base}_{n}"
    return delim


def render(entry):
    text = entry["text"]

    # $(cat <<EOF) strips *all* trailing newlines, and a heredoc always adds
    # one. So the body is split: everything up to the trailing run goes in the
    # heredoc verbatim, and the exact trailing run is re-attached by printf.
    # Get this wrong and every paste gains or loses a newline — which in a chat
    # box or a terminal means submitting instead of typing.
    core = text.rstrip("\n")
    fmt = "%s" + "\\n" * (len(text) - len(core))
    delim = heredoc_delimiter(core)

    return f"""#!/bin/bash
#
# {MARKER}
# Source: raycast/text/{entry['source'].name}
# Do not edit this file — edit the source and re-run ./scripts/build-raycast-text-paste-scripts.py
#
# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title {entry['name']}
# @raycast.mode silent
# @raycast.packageName Text

# Optional parameters:
# @raycast.icon {entry['icon']}

# Documentation:
# @raycast.description Paste the "{entry['name']}" text into the frontmost app
# @raycast.author joshlebed
# @raycast.authorURL https://github.com/joshlebed

# Raycast runs scripts without a UTF-8 locale; without this, pbcopy/pbpaste
# transcode non-ASCII text to MacRoman (and drop emoji).
export LC_CTYPE=UTF-8

ORIGINAL=$(pbpaste)

TEXT=$(cat <<'{delim}'
{core}
{delim}
)

printf '{fmt}' "$TEXT" | pbcopy
osascript -e 'tell application "System Events" to keystroke "v" using command down'

# Give the paste time to land before putting the clipboard back. Restores text
# only — a non-text clipboard (an image, files) is not preserved.
sleep 0.15
printf '%s' "$ORIGINAL" | pbcopy
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify generated output matches the sources; write nothing")
    args = ap.parse_args()

    files = sorted(SRC_DIR.glob("*.txt"))
    if not files:
        print(f"error: no .txt files in {SRC_DIR}", file=sys.stderr)
        return 1

    entries, errors = [], []
    for f in files:
        try:
            entries.append(parse(f))
        except ValueError as e:
            errors.append(str(e))

    # Two sources with the same name would render to the same filename, so one
    # would silently overwrite the other.
    seen = {}
    for e in entries:
        seen.setdefault(slug(e["name"]), []).append(e["source"].name)
    for key, owners in seen.items():
        if len(owners) > 1:
            errors.append(f"name collision on {key!r}: {', '.join(owners)}")

    if errors:
        for e in errors:
            print(f"error: {e}", file=sys.stderr)
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    wanted = {OUT_DIR / f"{slug(e['name'])}.sh": render(e) for e in entries}

    stale = [p for p in OUT_DIR.glob("*.sh")
             if p not in wanted and MARKER in p.read_text(encoding="utf-8", errors="replace")]
    drifted = [p for p, c in wanted.items()
               if not p.exists() or p.read_text(encoding="utf-8") != c]

    if args.check:
        if stale or drifted:
            for p in drifted:
                print(f"out of date: {p.relative_to(REPO)}", file=sys.stderr)
            for p in stale:
                print(f"stale: {p.relative_to(REPO)}", file=sys.stderr)
            print("run ./scripts/build-raycast-text-paste-scripts.py", file=sys.stderr)
            return 1
        print(f"{len(wanted)} commands up to date")
        return 0

    for path, content in wanted.items():
        path.write_text(content, encoding="utf-8")
        path.chmod(0o755)
    for path in stale:
        path.unlink()

    msg = f"{len(wanted)} commands -> {OUT_DIR.relative_to(REPO)}"
    if stale:
        msg += f" ({len(stale)} stale removed)"
    print(msg)
    return 0


if __name__ == "__main__":
    sys.exit(main())
